# The Datasets Library

## Working with local and remote datasets

In [1]:
# loading a local dataset
!wget https://github.com/crux82/squad-it/raw/master/SQuAD_it-train.json.gz
!wget https://github.com/crux82/squad-it/raw/master/SQuAD_it-test.json.gz

--2026-08-09 09:14:53--  https://github.com/crux82/squad-it/raw/master/SQuAD_it-train.json.gz
Resolving github.com (github.com)... 140.82.121.3
Connecting to github.com (github.com)|140.82.121.3|:443... connected.
HTTP request sent, awaiting response... 302 Found
Location: https://raw.githubusercontent.com/crux82/squad-it/master/SQuAD_it-train.json.gz [following]
--2026-08-09 09:14:54--  https://raw.githubusercontent.com/crux82/squad-it/master/SQuAD_it-train.json.gz
Resolving raw.githubusercontent.com (raw.githubusercontent.com)... 185.199.108.133, 185.199.110.133, 185.199.109.133, ...
Connecting to raw.githubusercontent.com (raw.githubusercontent.com)|185.199.108.133|:443... connected.
HTTP request sent, awaiting response... 200 OK
Length: 7725286 (7.4M) [application/octet-stream]
Saving to: ‘SQuAD_it-train.json.gz’

SQuAD_it-train.json 100%[===================>]   7.37M  12.6MB/s    in 0.6s

2026-08-09 09:14:55 (12.6 MB/s) - ‘SQuAD_it-train.json.gz’ saved [7725286/7725286]

--2026-08-09 09:14:56--  https://github.com/crux82/squad-it/raw/master/SQuAD_it-test.json.gz
Resolving github.com (github.com)... 140.82.121.3
Connecting to github.com (github.com)|140.82.121.3|:443... connected.
HTTP request sent, awaiting response... 302 Found
Location: https://raw.githubusercontent.com/crux82/squad-it/master/SQuAD_it-test.json.gz [following]
--2026-08-09 09:14:56--  https://raw.githubusercontent.com/crux82/squad-it/master/SQuAD_it-test.json.gz
Resolving raw.githubusercontent.com (raw.githubusercontent.com)... 185.199.108.133, 185.199.110.133, 185.199.111.133, ...
Connecting to raw.githubusercontent.com (raw.githubusercontent.com)|185.199.108.133|:443... connected.
HTTP request sent, awaiting response... 200 OK
Length: 1051245 (1.0M) [application/octet-stream]
Saving to: ‘SQuAD_it-test.json.gz’

SQuAD_it-test.json. 100%[===================>]   1.00M  2.41MB/s    in 0.4s

2026-08-09 09:14:57 (2.41 MB/s) - ‘SQuAD_it-test.json.gz’ saved [1051245/1051245]

In [2]:
!gzip -dvk SQuAD_it-*.json.gz

SQuAD_it-test.json.gz:	 87.5% -- created SQuAD_it-test.json
SQuAD_it-train.json.gz:	 82.3% -- created SQuAD_it-train.json

In [3]:
from datasets import load_dataset

squad_it_dataset = load_dataset("json", data_files="SQuAD_it-test.json", field="data")

/home/toor/Desktop/all/LLM-Transformers/.venv/lib/python3.11/site-packages/tqdm/auto.py:21: TqdmWarning: IProgress not found. Please update jupyter and ipywidgets. See https://ipywidgets.readthedocs.io/en/stable/user_install.html
  from .autonotebook import tqdm as notebook_tqdm
Generating train split: 48 examples [00:00, 229.46 examples/s]

In [4]:
squad_it_dataset

DatasetDict({
    train: Dataset({
        features: ['paragraphs', 'title'],
        num_rows: 48
    })
})

In [5]:
squad_it_dataset["train"][0]

{'paragraphs': [{'qas': [{'question': 'Quando è iniziata la crisi petrolifera del 1973?',
     'answers': [{'text': 'ottobre 1973', 'answer_start': 43},
      {'text': 'ottobre 1973', 'answer_start': 43},
      {'text': 'ottobre 1973', 'answer_start': 43},
      {'text': 'ottobre', 'answer_start': 43},
      {'text': '1973', 'answer_start': 25}],
     'id': '5725b33f6a3fe71400b8952d'},
    {'question': 'Quando è stata la seconda crisi petrolifera?',
     'answers': [{'text': '1979', 'answer_start': 658},
      {'text': '1979', 'answer_start': 658},
      {'text': '1979', 'answer_start': 658},
      {'text': '1979', 'answer_start': 658},
      {'text': '1979', 'answer_start': 658}],
     'id': '5725b33f6a3fe71400b8952f'},
    {'question': 'Qual è stato un altro termine utilizzato per la crisi petrolifera?',
     'answers': [{'text': 'shock', 'answer_start': 471},
      {'text': 'shock', 'answer_start': 471},
      {'text': 'shock', 'answer_start': 471}],
     'id': '5725b33f6a3fe71400b89530'},
    {'question': "Chi ha proclamato l' embargo petrolifero?",
     'answers': [{'text': "membri dell' Organizzazione dei Paesi esportatori di petrolio arabo",
       'answer_start': 65},
      {'text': "membri dell' Organizzazione dei Paesi esportatori di petrolio arabo",
       'answer_start': 65},
      {'text': 'Organizzazione dei Paesi esportatori di petrolio arabo',
       'answer_start': 78},
      {'text': "membri dell' Organizzazione dei Paesi esportatori di petrolio arabo",
       'answer_start': 65},
      {'text': 'OAPEC', 'answer_start': 134}],
     'id': '5725b33f6a3fe71400b89531'}],
   'context': 'La crisi petrolifera del 1973 iniziò nell\' ottobre 1973 quando i membri dell\' Organizzazione dei Paesi esportatori di petrolio arabo (OAPEC, composta dai membri arabi dell\' OPEC più Egitto e Siria) proclamarono un embargo petrolifero. Alla fine dell\' embargo, nel marzo 1974, il prezzo del petrolio era salito da 3 dollari al barile a quasi 12 dollari a livello mondiale; i prezzi americani erano notevolmente più elevati. L\' embargo ha causato una crisi petrolifera, o "shock", con molti effetti a breve e lungo termine sulla politica globale e sull\' economia globale. Più tardi fu chiamato il "primo shock petrolifero", seguito dalla crisi petrolifera del 1979, definita il "secondo shock petrolifero".'},
  {'qas': [{'question': 'Perchè le nazioni europee e il Giappone si sono separati dagli Stati Uniti durante la crisi?',
     'answers': [{'text': 'evitare di essere presi di mira dal boicottaggio',
       'answer_start': 243},
      {'text': 'evitare di essere presi di mira dal boicottaggio',
       'answer_start': 243},
      {'text': 'evitare di essere presi di mira dal boicottaggio',
       'answer_start': 243},
      {'text': 'evitare di essere presi di mira dal boicottaggio',
       'answer_start': 243},
      {'text': 'evitare di essere presi di mira dal boicottaggio',
       'answer_start': 243}],
     'id': '5725b5a689a1e219009abd28'},
    {'question': 'In quale data Henry Kissinger ha negoziato un ritiro di truppe israeliane dalla penisola del Sinai?',
     'answers': [{'text': '18 gennaio 1974', 'answer_start': 625},
      {'text': '18 gennaio 1974', 'answer_start': 625},
      {'text': '18 gennaio 1974,', 'answer_start': 625}],
     'id': '5725b5a689a1e219009abd29'},
    {'question': "Quando hanno revocato l' embargo i produttori di petrolio arabi?",
     'answers': [{'text': 'marzo 1974', 'answer_start': 935},
      {'text': 'marzo 1974', 'answer_start': 935},
      {'text': 'marzo 1974', 'answer_start': 935},
      {'text': 'marzo 1974', 'answer_start': 935},
      {'text': 'marzo 1974', 'answer_start': 935}],
     'id': '5725b5a689a1e219009abd2a'}],
   'context': "La crisi ha avuto un forte impatto sulle relazioni internazionali e ha creato una frattura all' interno della NATO. Alcune nazioni europee e il Giappone hanno cercato di dissociarsi dalla politica estera degli Stati Uniti in Medio Oriente per evitare di essere presi di mira dal boicottaggio. I produttori arabi di petrolio hanno collegato eventuali cambiamenti politici futuri alla pace tra i belligeranti. Per affrontare questo problema, l' amministrazione Nixon ha avviato negoziati multilaterali con i combattenti. Hanno fatto in modo che Israele tornasse dalla penisola del Sinai e dalle alture del Golan. A partire dal 18 gennaio 1974, il segretario di Stato statunitense Henry Kissinger aveva negoziato il ritiro di una truppa israeliana da alcune parti della penisola del Sinai. La promessa di un accordo negoziato tra Israele e Siria è stata sufficiente per convincere i produttori di petrolio arabo a revocare l' embargo nel marzo 1974."},
  {'qas': [{'question': "Quando si sono ritirati gli Stati Uniti dall' accordo di Bretton Woods?",
     'answers': [{'text': 'Il 15 agosto 1971', 'answer_start': 0},
      {'text': '15 agosto 1971', 'answer_start': 3},
      {'text': '15 agosto 1971', 'answer_start': 3},
      {'text': '15 agosto 1971', 'answer_start': 3},
      {'text': '15 agosto 1971', 'answer_start': 3}],
     'id': '5725b76389a1e219009abd4a'},
    {'question': "Perchè c' è stato un deprezzamento dei dollari delle nazioni industrializzate?",
     'answers': [{'text': 'i paesi industrializzati hanno aumentato le loro riserve',
       'answer_start': 633}],
     'id': '5725b76389a1e219009abd4c'},
    {'question': "Quando l' olio ha cominciato ad ottenere prezzi in termini di oro?",
     'answers': [{'text': 'Nel settembre 1971', 'answer_start': 965},
      {'text': 'settembre 1971', 'answer_start': 969},
      {'text': 'settembre 1971', 'answer_start': 969},
      {'text': 'settembre 1971', 'answer_start': 969},
      {'text': 'settembre 1971', 'answer_start': 969}],
     'id': '5725b76389a1e219009abd4d'}],
   'context': 'Il 15 agosto 1971, gli Stati Uniti uscirono unilateralmente dall\' accordo di Bretton Woods. Gli Stati Uniti hanno abbandonato l\' Gold Exchange Standard, in base al quale il valore del dollaro era stato ancorato al prezzo dell\' oro e tutte le altre valute erano ancorate al dollaro, il cui valore era lasciato "fluttuare" (aumento e diminuzione a seconda della domanda del mercato). Poco dopo, seguì la Gran Bretagna, facendo fluttuare la lira sterlina. Gli altri paesi industrializzati seguirono l\' esempio con le rispettive valute. Anticipando che i valori valutari fluttuassero in modo imprevedibile per un certo periodo di tempo, i paesi industrializzati hanno aumentato le loro riserve (ampliando le loro scorte di moneta) in quantità molto maggiori di prima. Il risultato è stato un deprezzamento del dollaro e delle valute di altri paesi industrializzati. Poichè il prezzo del petrolio era in dollari, il reddito reale dei produttori di petrolio è diminuito. Nel settembre 1971, l\' OPEC ha pubblicato un comunicato congiunto nel quale dichiarava che, da quel momento in poi, il prezzo del petrolio sarebbe stato fissato a un importo fisso di oro.'},
  {'qas': [{'question': 'Dal 1947 al 1967, quanto è aumentato il prezzo del petrolio?',
     'answers': [{'text': "è aumentato di meno del 2% all' anno",
       'answer_start': 186},
      {'text': "meno del 2% all' anno", 'answer_start': 201},
      {'text': "meno del 2% all' anno", 'answer_start': 201},
      {'text': "di meno del 2% all' anno", 'answer_start': 198},
      {'text': "meno del 2% all' anno", 'answer_start': 201}],
     'id': '5725b92e38643c19005acbd3'},
    {'question': "Quando ha iniziato l' OPEC a riadattare i prezzi del petrolio?",
     'answers': [{'text': 'Dopo il 1971', 'answer_start': 45},
      {'text': '1971', 'answer_start': 53},
      {'text': 'Dopo il 1971', 'answer_start': 45},
      {'text': '1971', 'answer_start': 53}],
     'id': '5725b92e38643c19005acbd4'},
    {'question': "Quando l' olio è tornato ai suoi livelli di Bretton Woods?",
     'answers': [{'text': '1974', 'answer_start': 585}],
     'id': '5725b92e38643c19005acbd5'}],
   'context': 'Questo ha contribuito alla "scossa da olio". Dopo il 1971, l\' OPEC ha tardato ad adeguare i prezzi per riflettere tale deprezzamento. Dal 1947 al 1967, il prezzo del petrolio in dollari è aumentato di meno del 2% all\' anno. Fino allo shock petrolifero, il prezzo era rimasto abbastanza stabile anche nei confronti di altre valute e materie prime. I ministri dell\' OPEC non avevano sviluppato meccanismi istituzionali per aggiornare i prezzi in sintonia con le mutevoli condizioni di mercato, per cui i loro redditi reali sono rimasti indietro. I sostanziali aumenti di prezzo del 1973-1974 hanno ampiamente riportato i loro prezzi e i corrispondenti redditi ai livelli di Bretton Woods in termini di materie prime come l\' oro.'},
  {'qas': [{'question': "Quando la Siria e l' Egitto hanno lanciato un attacco a sorpresa contro Israele?",
     'answers': [{'text': '6 ottobre 1973', 'answer_start': 3},
      {'text': '6 ottobre 1973', 'answer_start': 3},
      {'text': '6 ottobre 1973', 'answer_start': 3},
      {'text': '6 ottobre 1973', 'answer_start': 3}],
     'id': '5725bad5271a42140099d0bd'},
    {'question': "Quante volte di più le altre nazioni hanno dovuto pagare per il petrolio dopo l' attacco a sorpresa?",
     'answers': [{'text': 'dieci volte di più', 'answer_start': 851},
      {'text': 'dieci', 'answer_start': 851},
      {'text': 'Iran', 'answer_start': 289},
      {'text': 'dieci', 'answer_start': 851}],
     'id': '5725bad5271a42140099d0be'},
    {'question': "Perchè lo scià d' Iran ha rilasciato un' intervista?",
     'answers': [{'text': '.', 'answer_start': 139}],
     'id': '5725bad5271a42140099d0bf'}],
   'context': 'Il 6 ottobre 1973, la Siria e l\' Egitto, con il sostegno di altre nazioni arabe, lanciarono un attacco a sorpresa su Israele, su Yom Kippur. Questo rinnovo delle ostilità nel conflitto arabo-israeliano ha liberato la pressione economica sottostante sui prezzi del petrolio. All\' epoca, l\' Iran era il secondo esportatore mondiale di petrolio e un vicino alleato degli Stati Uniti. Settimane più tardi, lo scià d\' Iran ha detto in un\' intervista:"Naturalmente[il prezzo del petrolio] sta andando a salire Certamente! E come! Avete[Paesi occidentali] aumentato il prezzo del grano che ci vendete del 300 per cento, e lo stesso per zucchero e cemento. Voi comprate il nostro petrolio greggio e rivendete a noi, raffinato come petrolchimico, a cento volte il prezzo che ci avete pagato E\' giusto che d\' ora in poi si paghi di più per il petrolio. Diciamo dieci volte di più". Il 6 ottobre 1973.'},
  {'qas': [{'question': "Perchè l' OPEC ha portato il prezzo del petrolio a 5,11 dollari?",
     'answers': [{'text': 'In risposta agli aiuti americani a Israele',
       'answer_start': 0},
      {'text': 'In risposta agli aiuti americani a Israele',
       'answer_start': 0},
      {'text': 'In risposta agli aiuti americani a Israele',
       'answer_start': 0},
      {'text': 'In risposta agli aiuti americani a Israele',
       'answer_start': 0}],
     'id': '5725bcb6271a42140099d0eb'},
    {'question': 'Quando hanno portato il prezzo del petrolio a 5,11 dollari?',
     'answers': [{'text': '16 ottobre 1973,', 'answer_start': 47},
      {'text': '16 ottobre 1973', 'answer_start': 47},
      {'text': '16 ottobre 1973', 'answer_start': 47},
      {'text': '16 ottobre 1973', 'answer_start': 47},
      {'text': '16 ottobre 1973', 'answer_start': 47}],
     'id': '5725bcb6271a42140099d0ec'},
    {'question': 'Perchè i ministri del petrolio hanno accettato di tagliare la produzione petrolifera?',
     'answers': [{'text': 'fino al raggiungimento dei loro obiettivi economici e politici',
       'answer_start': 419},
      {'text': 'In risposta agli aiuti americani a Israele',
       'answer_start': 0},
      {'text': "l' OPEC ha aumentato il prezzo del petrolio",
       'answer_start': 64},
      {'text': 'fino al raggiungimento dei loro obiettivi economici e politici',
       'answer_start': 419}],
     'id': '5725bcb6271a42140099d0ed'},
    {'question': "A quanto ammontavano gli aiuti d' urgenza a Israele?",
     'answers': [{'text': '$2,2 miliardi', 'answer_start': 796},
      {'text': '$2,2 miliardi', 'answer_start': 796},
      {'text': '$2,2 miliardi', 'answer_start': 796},
      {'text': '$2,2 miliardi', 'answer_start': 796},
      {'text': '$2,2 miliardi', 'answer_start': 796}],
     'id': '5725bcb6271a42140099d0ee'},
    {'question': "Perchè l' OPEC ha bloccato le consegne di petrolio negli Stati Uniti?",
     'answers': [{'text': "Nixon ha chiesto al Congresso di stanziare 2,2 miliardi di dollari in aiuti d' emergenza a Israele",
       'answer_start': 497},
      {'text': 'l\' OAPEC ha proclamato l\' embargo che limitava le esportazioni verso vari paesi e bloccava tutte le consegne di petrolio negli Stati Uniti come "principale paese ostile"',
       'answer_start': 1123},
      {'text': "l' OAPEC ha proclamato l' embargo che limitava le esportazioni verso vari paesi",
       'answer_start': 1123}],
     'id': '5725bcb6271a42140099d0ef'}],
   'context': 'In risposta agli aiuti americani a Israele, il 16 ottobre 1973, l\' OPEC ha aumentato il prezzo del petrolio del 70%, portandolo a 5,11 dollari al barile. Il giorno successivo, i ministri del petrolio hanno approvato l\' embargo, con una riduzione della produzione del cinque per cento rispetto alla produzione di settembre e hanno deciso di continuare a ridurre la produzione con incrementi mensili del cinque per cento fino al raggiungimento dei loro obiettivi economici e politici. Il 19 ottobre Nixon ha chiesto al Congresso di stanziare 2,2 miliardi di dollari in aiuti d\' emergenza a Israele, inclusi 1,5 miliardi di dollari in sovvenzioni a fondo perduto. George Lenczowski osserva:"Le forniture militari non esauriscono la volontà di Nixon di impedire il crollo di Israele Questa decisione[$2,2 miliardi] ha scatenato una risposta collettiva dell\' OPEC". La Libia ha immediatamente annunciato che avrebbe embargo sulle spedizioni di petrolio verso gli Stati Uniti. L\' Arabia Saudita e gli altri Stati arabi produttori di petrolio hanno aderito all\' embargo il 20 ottobre 1973. In occasione della riunione del Kuwait, l\' OAPEC ha proclamato l\' embargo che limitava le esportazioni verso vari paesi e bloccava tutte le consegne di petrolio negli Stati Uniti come "principale paese ostile".'},
  {'qas': [{'question': "Quanto ha speso l' Arabia Saudita per diffondere il wahhabismo?",
     'answers': [{'text': 'oltre 100 miliardi di dollari',
       'answer_start': 442},
      {'text': 'oltre 100 miliardi di dollari', 'answer_start': 442},
      {'text': 'oltre 100 miliardi di dollari', 'answer_start': 442},
      {'text': 'oltre 100 miliardi di dollari', 'answer_start': 442},
      {'text': '100 miliardi di dollari', 'answer_start': 448}],
     'id': '57261dab38643c19005ad037'},
    {'question': "Quale gruppo ha beneficiato dei fondi distribuiti dalla fondazione al-Haramain, l' associazione religiosa al-Haramain Foundation?",
     'answers': [{'text': 'Al-Qaeda e i Talebani', 'answer_start': 780},
      {'text': 'violenti gruppi estremisti sunniti come Al-Qaeda e i Talebani',
       'answer_start': 740},
      {'text': 'Al-Qaeda e i Talebani', 'answer_start': 780},
      {'text': 'Al-Qaeda e i Talebani', 'answer_start': 780},
      {'text': 'Al-Qaeda e i Talebani', 'answer_start': 780}],
     'id': '57261dab38643c19005ad038'},
    {'question': "Una parte delle entrate è stata destinata all' acquisto di armi che hanno esacerbato le tensioni politiche, soprattutto in quale area?",
     'answers': [{'text': 'Medio Oriente', 'answer_start': 400},
      {'text': 'Medio Oriente', 'answer_start': 400},
      {'text': 'Medio Oriente', 'answer_start': 400},
      {'text': 'Medio Oriente', 'answer_start': 400},
      {'text': 'Medio Oriente', 'answer_start': 400}],
     'id': '57261dab38643c19005ad039'},
    {'question': 'Qual è una delle ragioni per cui i paesi sottosviluppati hanno ricevuto aiuti dal reddito petrolifero?',
     'answers': [{'text': 'contrazione della domanda occidentale',
       'answer_start': 262},
      {'text': 'contrazione della domanda occidentale', 'answer_start': 262},
      {'text': 'contrazione della domanda occidentale', 'answer_start': 262}],
     'id': '57261dab38643c19005ad03a'},
    {'question': "Che cos' è una interpretazione fondamentalista dell' Islam chiamata?",
     'answers': [{'text': 'Wahhabismo', 'answer_start': 586},
      {'text': 'Wahhabismo', 'answer_start': 586},
      {'text': 'Wahhabismo', 'answer_start': 586},
      {'text': 'Wahhabismo', 'answer_start': 586},
      {'text': 'Wahhabismo', 'answer_start': 586}],
     'id': '57261dab38643c19005ad03b'}],
   'context': "Una parte del reddito è stata erogata sotto forma di aiuti ad altri paesi sottosviluppati le cui economie erano state catturate tra l' aumento dei prezzi del petrolio e la diminuzione dei prezzi delle materie prime destinate all' esportazione, in un contesto di contrazione della domanda occidentale. Molto è andato per gli acquisti di armi che hanno esacerbato le tensioni politiche, soprattutto in Medio Oriente. L' Arabia Saudita ha speso oltre 100 miliardi di dollari nei decenni successivi per contribuire a diffondere la sua interpretazione fondamentalista dell' Islam, noto come Wahhabismo, in tutto il mondo, attraverso organizzazioni di beneficenza religiose come la Fondazione al-Haramain, che spesso ha distribuito fondi anche a violenti gruppi estremisti sunniti come Al-Qaeda e i Talebani."},
  {'qas': [{'question': 'Gli studiosi hanno dichiarato che esisteva già un accordo esistente tra due parti prima di tale data?',
     'answers': [{'text': '1973', 'answer_start': 133},
      {'text': '1973', 'answer_start': 133},
      {'text': '1973', 'answer_start': 133},
      {'text': '1973', 'answer_start': 133}],
     'id': '57261f9f271a42140099d4ab'},
    {'question': "I gruppi d' interesse e le agenzie governative che si occupavano di energia non erano all' altezza di chi?",
     'answers': [{'text': 'Kissinger', 'answer_start': 431},
      {'text': 'Kissinger', 'answer_start': 431},
      {'text': 'Kissinger', 'answer_start': 431},
      {'text': 'Kissinger', 'answer_start': 431}],
     'id': '57261f9f271a42140099d4ac'}],
   'context': 'Negli Stati Uniti, gli studiosi sostengono che esisteva già un accordo negoziato basato sull\' uguaglianza tra le due parti prima del 1973. La possibilità che il Medio Oriente potesse diventare un altro confronto di superpotenza con l\' URSS era più preoccupante per gli Stati Uniti che per il petrolio. Inoltre, i gruppi d\' interesse e le agenzie governative più preoccupati per l\' energia non erano all\' altezza della dominanza di Kissinger. Negli Stati Uniti la produzione, la distribuzione e le perturbazioni dei prezzi "sono state ritenute responsabili di recessioni, periodi di eccessiva inflazione, riduzione della produttività e minore crescita economica".'},
  {'qas': [{'question': "Che cosa influisce negativamente sull' economia statunitense?",
     'answers': [{'text': "L' embargo", 'answer_start': 0},
      {'text': "L' embargo", 'answer_start': 0},
      {'text': "L' embargo", 'answer_start': 0},
      {'text': 'embargo', 'answer_start': 3}],
     'id': '5726241189a1e219009ac2de'},
    {'question': "Quale problema consiste sia nell' impatto inflazionistico che deflazionistico?",
     'answers': [{'text': 'problemi macroeconomici', 'answer_start': 308}],
     'id': '5726241189a1e219009ac2df'},
    {'question': "La crisi petrolifera ha indotto le compagnie petrolifere ad aumentare l' offerta di petrolio in quale area?",
     'answers': [{'text': 'Artico', 'answer_start': 546},
      {'text': 'Artico', 'answer_start': 546},
      {'text': 'Artico', 'answer_start': 546},
      {'text': "l' Artico", 'answer_start': 543},
      {'text': "l' Artico", 'answer_start': 543}],
     'id': '5726241189a1e219009ac2e0'},
    {'question': 'Quanto tempo ci vuole perchè nuove aree abbiano una produzione significativa di petrolio?',

In [6]:
data_files = {"train":"SQuAD_it-train.json", "test": "SQuAD_it-test.json"}

squad_it_datasets = load_dataset("json", data_files=data_files, field="data")

squad_it_datasets

Generating train split: 442 examples [00:00, 469.97 examples/s]
Generating test split: 48 examples [00:00, 432.91 examples/s]

DatasetDict({
    train: Dataset({
        features: ['title', 'paragraphs'],
        num_rows: 442
    })
    test: Dataset({
        features: ['title', 'paragraphs'],
        num_rows: 48
    })
})

In [7]:
data_files = {"train": "SQuAD_it-train.json.gz", "test": "SQuAD_it-test.json.gz"}
squad_it_dataset = load_dataset("json", data_files=data_files, field="data")

Generating train split: 442 examples [00:01, 396.33 examples/s]
Generating test split: 48 examples [00:00, 249.40 examples/s]

## Loading a remote dataset

In [8]:
!curl -I https://raw.githubusercontent.com/crux82/squad-it/master/SQuAD_it-train.json.gz

HTTP/2 200
cache-control: max-age=300
content-security-policy: default-src 'none'; style-src 'unsafe-inline'; sandbox
content-type: application/octet-stream
etag: "e272cf7512a6e282d9ba7b7b220cc0516df5a3de8b3811f280956dcaee9689f4"
strict-transport-security: max-age=31536000
x-content-type-options: nosniff
x-frame-options: deny
x-xss-protection: 1; mode=block
x-github-request-id: 5D08:11BAD2:19F89B0:1D5F175:6A7813D5
x-github-edge-region: fra
accept-ranges: bytes
date: Sun, 09 Aug 2026 05:45:03 GMT
via: 1.1 varnish
x-served-by: cache-fra-eddf8230061-FRA
x-cache: HIT
x-cache-hits: 1
x-timer: S1786254304.593773,VS0,VE12
vary: Authorization,Accept-Encoding
access-control-allow-origin: *
cross-origin-resource-policy: cross-origin
x-fastly-request-id: 4282db215f517e643772f68bc4d0c101bebc0bf1
expires: Sun, 09 Aug 2026 05:50:03 GMT
source-age: 8
content-length: 7725286

In [9]:
import requests

url = "https://raw.githubusercontent.com/crux82/squad-it/master/SQuAD_it-train.json.gz"

r = requests.get(url)

print(r.status_code)
print(len(r.content))

200
7725286

In [10]:
url = "https://github.com/crux82/squad-it/raw/master/"
data_files = {
    "train": url + "SQuAD_it-train.json.gz",
    "test": url + "SQuAD_it-test.json.gz",
}
squad_it_dataset = load_dataset("json", data_files=data_files, field="data")

FileNotFoundError: http://https://github.com/crux82/squad-it/raw/master/SQuAD_it-train.json.gz

## Time to slice and dice

In [ ]:
!wget "https://archive.ics.uci.edu/ml/machine-learning-databases/00462/drugsCom_raw.zip"
!unzip drugsCom_raw.zip

--2026-08-09 09:29:54--  https://archive.ics.uci.edu/ml/machine-learning-databases/00462/drugsCom_raw.zip
Resolving archive.ics.uci.edu (archive.ics.uci.edu)... 128.195.10.252
Connecting to archive.ics.uci.edu (archive.ics.uci.edu)|128.195.10.252|:443... connected.
HTTP request sent, awaiting response... 200 OK
Length: unspecified
Saving to: ‘drugsCom_raw.zip.1’

drugsCom_raw.zip.1      [ <=>                ]  41.00M   214KB/s    in 2m 29s

2026-08-09 09:32:25 (281 KB/s) - ‘drugsCom_raw.zip.1’ saved [42989872]

Archive:  drugsCom_raw.zip
replace drugsComTest_raw.tsv? [y]es, [n]o, [A]ll, [N]one, [r]ename:

In [1]:
from datasets import load_dataset

data_files = {"train": "drugsComTrain_raw.tsv", "test":"drugsComTest_raw.tsv"}

drug_dataset = load_dataset("csv", data_files=data_files, delimiter="\t")

drug_dataset

/home/toor/Desktop/all/LLM-Transformers/.venv/lib/python3.11/site-packages/tqdm/auto.py:21: TqdmWarning: IProgress not found. Please update jupyter and ipywidgets. See https://ipywidgets.readthedocs.io/en/stable/user_install.html
  from .autonotebook import tqdm as notebook_tqdm

DatasetDict({
    train: Dataset({
        features: ['Unnamed: 0', 'drugName', 'condition', 'review', 'rating', 'date', 'usefulCount'],
        num_rows: 161297
    })
    test: Dataset({
        features: ['Unnamed: 0', 'drugName', 'condition', 'review', 'rating', 'date', 'usefulCount'],
        num_rows: 53766
    })
})

In [2]:
drug_sample = drug_dataset["train"].shuffle(seed=42).select(range(1000))

drug_sample[:3]

{'Unnamed: 0': [87571, 178045, 80482],
 'drugName': ['Naproxen', 'Duloxetine', 'Mobic'],
 'condition': ['Gout, Acute', 'ibromyalgia', 'Inflammatory Conditions'],
 'review': ['"like the previous person mention, I&#039;m a strong believer of aleve, it works faster for my gout than the prescription meds I take. No more going to the doctor for refills.....Aleve works!"',
  '"I have taken Cymbalta for about a year and a half for fibromyalgia pain. It is great\r\nas a pain reducer and an anti-depressant, however, the side effects outweighed \r\nany benefit I got from it. I had trouble with restlessness, being tired constantly,\r\ndizziness, dry mouth, numbness and tingling in my feet, and horrible sweating. I am\r\nbeing weaned off of it now. Went from 60 mg to 30mg and now to 15 mg. I will be\r\noff completely in about a week. The fibro pain is coming back, but I would rather deal with it than the side effects."',
  '"I have been taking Mobic for over a year with no side effects other than an elevated blood pressure.  I had severe knee and ankle pain which completely went away after taking Mobic.  I attempted to stop the medication however pain returned after a few days."'],
 'rating': [9.0, 3.0, 10.0],
 'date': ['September 2, 2015', 'November 7, 2011', 'June 5, 2013'],
 'usefulCount': [36, 13, 128]}

In [3]:
for split in drug_dataset.keys():
    assert len(drug_dataset[split]) == len(drug_dataset[split].unique("Unnamed: 0"))

In [4]:
drug_dataset = drug_dataset.rename_column(
    original_column_name="Unnamed: 0",
    new_column_name="patient_id"
)

drug_dataset

DatasetDict({
    train: Dataset({
        features: ['patient_id', 'drugName', 'condition', 'review', 'rating', 'date', 'usefulCount'],
        num_rows: 161297
    })
    test: Dataset({
        features: ['patient_id', 'drugName', 'condition', 'review', 'rating', 'date', 'usefulCount'],
        num_rows: 53766
    })
})

In [5]:
drug_dataset["train"]["patient_id"]

Column([206461, 95260, 92703, 138000, 35696])

In [6]:
drug_dataset["train"]["condition"]

Column(['Left Ventricular Dysfunction', 'ADHD', 'Birth Control', 'Birth Control', 'Opiate Dependence'])

In [7]:
def lowercase_condition(example):
    return {"condition":example["condition"].lower()}

drug_dataset.map(lowercase_condition)

Map:   0%|          | 30/161297 [00:00<01:12, 2217.68 examples/s]

AttributeError: 'NoneType' object has no attribute 'lower'

In [8]:
def filter_nones(x):
    return x["condition"] is not None

In [9]:
(lambda base, heigh : 0.5 * base * heigh)(4, 8)

16.0

In [10]:
drug_dataset = drug_dataset.filter(lambda x: x["condition"] is not None)

In [11]:
drug_dataset = drug_dataset.map(lowercase_condition)
drug_dataset["train"]["condition"][:3]

['left ventricular dysfunction', 'adhd', 'birth control']

## Creating new columns

In [12]:
def compute_review_length(example):
    return {"review_length": len(example["review"].split())}

In [13]:
drug_dataset = drug_dataset.map(compute_review_length)

drug_dataset["train"][0]

{'patient_id': 206461,
 'drugName': 'Valsartan',
 'condition': 'left ventricular dysfunction',
 'review': '"It has no side effect, I take it in combination of Bystolic 5 Mg and Fish Oil"',
 'rating': 9.0,
 'date': 'May 20, 2012',
 'usefulCount': 27,
 'review_length': 17}

In [14]:
drug_dataset["train"].sort("review_length")[:3]

{'patient_id': [111469, 13653, 53602],
 'drugName': ['Ledipasvir / sofosbuvir',
  'Amphetamine / dextroamphetamine',
  'Alesse'],
 'condition': ['hepatitis c', 'adhd', 'birth control'],
 'review': ['"Headache"', '"Great"', '"Awesome"'],
 'rating': [10.0, 10.0, 10.0],
 'date': ['February 3, 2015', 'October 20, 2009', 'November 23, 2015'],
 'usefulCount': [41, 3, 0],
 'review_length': [1, 1, 1]}

In [15]:
drug_dataset = drug_dataset.filter(lambda x: x["review_length"] > 30)
drug_dataset.num_rows

{'train': 138514, 'test': 46108}

In [16]:
import html

text = "I&#039;m a transformer called BERT"
html.unescape(text)

"I'm a transformer called BERT"

In [17]:
drug_dataset = drug_dataset.map(lambda x : {"review":html.unescape(x["review"])})
drug_dataset

Map: 100%|██████████| 138514/138514 [00:07<00:00, 17854.16 examples/s]
Map: 100%|██████████| 46108/46108 [00:02<00:00, 17885.28 examples/s]

DatasetDict({
    train: Dataset({
        features: ['patient_id', 'drugName', 'condition', 'review', 'rating', 'date', 'usefulCount', 'review_length'],
        num_rows: 138514
    })
    test: Dataset({
        features: ['patient_id', 'drugName', 'condition', 'review', 'rating', 'date', 'usefulCount', 'review_length'],
        num_rows: 46108
    })
})

In [18]:
drug_dataset["train"]["review"][:2]

['"My son is halfway through his fourth week of Intuniv. We became concerned when he began this last week, when he started taking the highest dose he will be on. For two days, he could hardly get out of bed, was very cranky, and slept for nearly 8 hours on a drive home from school vacation (very unusual for him.) I called his doctor on Monday morning and she said to stick it out a few days. See how he did at school, and with getting up in the morning. The last two days have been problem free. He is MUCH more agreeable than ever. He is less emotional (a good thing), less cranky. He is remembering all the things he should. Overall his behavior is better. \r\nWe have tried many different medications and so far this is the most effective."',
 '"I used to take another oral contraceptive, which had 21 pill cycle, and was very happy- very light periods, max 5 days, no other side effects. But it contained hormone gestodene, which is not available in US, so I switched to Lybrel, because the ingredients are similar. When my other pills ended, I started Lybrel immediately, on my first day of period, as the instructions said. And the period lasted for two weeks. When taking the second pack- same two weeks. And now, with third pack things got even worse- my third period lasted for two weeks and now it\'s the end of the third week- I still have daily brown discharge.\r\nThe positive side is that I didn\'t have any other side effects. The idea of being period free was so tempting... Alas."']

In [19]:
new_drug_dataset = drug_dataset.map(
    lambda x : {"review":[html.unescape(o) for o in x["review"]]}, batched=True
)

Map: 100%|██████████| 138514/138514 [00:00<00:00, 536356.74 examples/s]
Map: 100%|██████████| 46108/46108 [00:00<00:00, 692291.61 examples/s]

In [22]:
from transformers import AutoTokenizer

tokenizer = AutoTokenizer.from_pretrained("bert-base-cased")

def tokenize_function(example):
    return tokenizer(example["review"], truncation=True)

In [23]:
%time tokenized_dataset = drug_dataset.map(tokenize_function, batched=True)

Map: 100%|██████████| 138514/138514 [00:08<00:00, 15604.26 examples/s]
Map: 100%|██████████| 46108/46108 [00:02<00:00, 16294.45 examples/s]

CPU times: user 1min 14s, sys: 953 ms, total: 1min 15s
Wall time: 11.7 s

In [26]:
tokenizer = AutoTokenizer.from_pretrained("bert-base-cased", use_fast=False)

def tokenize_function(example):
    return tokenizer(example["review"], truncation=True)

In [27]:
%time tokenized_dataset = drug_dataset.map(tokenize_function)

Map: 100%|██████████| 138514/138514 [01:29<00:00, 1541.23 examples/s]
Map: 100%|██████████| 46108/46108 [00:29<00:00, 1578.48 examples/s]

CPU times: user 1min 59s, sys: 925 ms, total: 2min
Wall time: 1min 59s

In [32]:
%time
slow_tokenizer = AutoTokenizer.from_pretrained("bert-base-cased", use_fast=False)

def slow_tokenize_function(examples):
    return slow_tokenizer(examples["review"], truncation=True)


tokenized_dataset = drug_dataset.map(slow_tokenize_function, batched=True, num_proc=9)

CPU times: user 7 μs, sys: 1 μs, total: 8 μs
Wall time: 17.9 μs

In [54]:
def tokenize_and_split(examples):
    return tokenizer(
        examples["review"],
        truncation=True,
        max_length=128,
        return_overflowing_tokens=True,
    )

In [55]:
result = tokenize_and_split(drug_dataset["train"][0])
s = [inp for inp in result["input_ids"]]

len(s)

128

In [56]:
tokenized_dataset = drug_dataset.map(tokenize_and_split, batched=True)

In [57]:
len(tokenized_dataset["train"]), len(drug_dataset["train"])

(138514, 138514)

In [58]:
tokenized_dataset

DatasetDict({
    train: Dataset({
        features: ['patient_id', 'drugName', 'condition', 'review', 'rating', 'date', 'usefulCount', 'review_length', 'overflowing_tokens', 'num_truncated_tokens', 'input_ids', 'token_type_ids', 'attention_mask'],
        num_rows: 138514
    })
    test: Dataset({
        features: ['patient_id', 'drugName', 'condition', 'review', 'rating', 'date', 'usefulCount', 'review_length', 'overflowing_tokens', 'num_truncated_tokens', 'input_ids', 'token_type_ids', 'attention_mask'],
        num_rows: 46108
    })
})

## From Datasets to DataFrames and back

In [60]:
drug_dataset.set_format("pandas")
drug_dataset["train"][:3]

,patient_id,drugName,condition,review,rating,date,usefulCount,review_length
0,95260,Guanfacine,adhd,"""My son is halfway through his fourth week of ...",8.0,"April 27, 2010",192,141
1,92703,Lybrel,birth control,"""I used to take another oral contraceptive, wh...",5.0,"December 14, 2009",17,134
2,138000,Ortho Evra,birth control,"""This is my first time using any form of birth...",8.0,"November 3, 2015",10,89

In [61]:
train_df = drug_dataset["train"][:]

In [62]:
train_df

,patient_id,drugName,condition,review,rating,date,usefulCount,review_length
0,95260,Guanfacine,adhd,"""My son is halfway through his fourth week of ...",8.0,"April 27, 2010",192,141
1,92703,Lybrel,birth control,"""I used to take another oral contraceptive, wh...",5.0,"December 14, 2009",17,134
2,138000,Ortho Evra,birth control,"""This is my first time using any form of birth...",8.0,"November 3, 2015",10,89
3,35696,Buprenorphine / naloxone,opiate dependence,"""Suboxone has completely turned my life around...",9.0,"November 27, 2016",37,124
4,155963,Cialis,benign prostatic hyperplasia,"""2nd day on 5mg started to work with rock hard...",2.0,"November 28, 2015",43,68
...,...,...,...,...,...,...,...,...
138509,164345,Junel 1.5 / 30,birth control,"""This would be my second month on Junel. I've ...",6.0,"May 27, 2015",0,71
138510,191035,Campral,alcohol dependence,"""I wrote my first report in Mid-October of 201...",10.0,"May 31, 2015",125,127
138511,127085,Metoclopramide,nausea/vomiting,"""I was given this in IV before surgey. I immed...",1.0,"November 1, 2011",34,50
138512,47128,Thyroid desiccated,underactive thyroid,"""I've been on thyroid medication 49 years, I s...",10.0,"September 19, 2015",79,136
138513,215220,Lubiprostone,"constipation, chronic","""I've had chronic constipation all my adult li...",9.0,"December 13, 2014",116,63

In [65]:
frequencies = (
    train_df["condition"].value_counts().to_frame().reset_index().rename(columns={"index":"condition", "count": "frequencies"})
)

In [67]:
frequencies.head()

       condition  frequencies
0  birth control        27655
1     depression         8023
2           acne         5209
3        anxiety         4991
4           pain         4744

In [68]:
from datasets import Dataset

freq_dataset = Dataset.from_pandas(frequencies)
freq_dataset

Dataset({
    features: ['condition', 'frequencies'],
    num_rows: 819
})

In [69]:
drug_dataset.reset_format()

## Create a Validation set

In [70]:
drug_dataset_clean = drug_dataset["train"].train_test_split(train_size=0.8, seed=42)

drug_dataset_clean["validation"] = drug_dataset_clean.pop("test")

drug_dataset_clean["test"] = drug_dataset["test"]

drug_dataset_clean

DatasetDict({
    train: Dataset({
        features: ['patient_id', 'drugName', 'condition', 'review', 'rating', 'date', 'usefulCount', 'review_length'],
        num_rows: 110811
    })
    validation: Dataset({
        features: ['patient_id', 'drugName', 'condition', 'review', 'rating', 'date', 'usefulCount', 'review_length'],
        num_rows: 27703
    })
    test: Dataset({
        features: ['patient_id', 'drugName', 'condition', 'review', 'rating', 'date', 'usefulCount', 'review_length'],
        num_rows: 46108
    })
})

## Saving a dataset

In [71]:
drug_dataset_clean.save_to_disk("drug-review")

Saving the dataset (1/1 shards): 100%|██████████| 110811/110811 [00:00<00:00, 176102.04 examples/s]
Saving the dataset (1/1 shards): 100%|██████████| 27703/27703 [00:00<00:00, 174738.75 examples/s]
Saving the dataset (1/1 shards): 100%|██████████| 46108/46108 [00:00<00:00, 1709261.46 examples/s]

In [72]:
from datasets import load_from_disk

drug_dataset_reload = load_from_disk("drug-review")

drug_dataset_reload

DatasetDict({
    train: Dataset({
        features: ['patient_id', 'drugName', 'condition', 'review', 'rating', 'date', 'usefulCount', 'review_length'],
        num_rows: 110811
    })
    validation: Dataset({
        features: ['patient_id', 'drugName', 'condition', 'review', 'rating', 'date', 'usefulCount', 'review_length'],
        num_rows: 27703
    })
    test: Dataset({
        features: ['patient_id', 'drugName', 'condition', 'review', 'rating', 'date', 'usefulCount', 'review_length'],
        num_rows: 46108
    })
})

In [73]:
for split, dataset in drug_dataset_clean.items():
    dataset.to_json(f"drug-reviews-{split}.jsonl")

Creating json from Arrow format: 100%|██████████| 111/111 [00:00<00:00, 142.33ba/s]
Creating json from Arrow format: 100%|██████████| 28/28 [00:00<00:00, 143.64ba/s]
Creating json from Arrow format: 100%|██████████| 47/47 [00:00<00:00, 317.73ba/s]

In [74]:
!head -n 1 drug-reviews-train.jsonl

{"patient_id":89879,"drugName":"Cyclosporine","condition":"keratoconjunctivitis sicca","review":"\"I have used Restasis for about a year now and have seen almost no progress.  For most of my life I've had red and bothersome eyes. After trying various eye drops, my doctor recommended Restasis.  He said it typically takes 3 to 6 months for it to really kick in but it never did kick in.  When I put the drops in it burns my eyes for the first 30 - 40 minutes.  I've talked with my doctor about this and he said it is normal but should go away after some time, but it hasn't. Every year around spring time my eyes get terrible irritated  and this year has been the same (maybe even worse than other years) even though I've been using Restasis for a year now. The only difference I notice was for the first couple weeks, but now I'm ready to move on.\"","rating":2.0,"date":"April 20, 2013","usefulCount":69,"review_length":147}

In [75]:
data_files = {
    "train": "drug-reviews-train.jsonl",
    "validation": "drug-reviews-validation.jsonl",
    "test": "drug-reviews-test.jsonl",
}
drug_dataset_reloaded = load_dataset("json", data_files=data_files)

Generating train split: 110811 examples [00:00, 340955.37 examples/s]
Generating validation split: 27703 examples [00:00, 435819.86 examples/s]
Generating test split: 46108 examples [00:00, 553795.62 examples/s]